name: Run action
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]
jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - run: sudo apt install libopencv-dev 
      - run: mkdir build
      - name: Compile and run tests
        working-directory: ./build
      - run: pwd
      - run: ls ./
      - run: cmake ./..
      - run: make
